### ISSUE TITLE
Host key verification failed when trying to clone in kubernetes

### ISSUE THREAD

**Issue by Kostanos** [alpine-docker/git#37]
Hey guys.
I'm trying to use this docker image in kubernetes environment.

This is my seetup:

```
      initContainers:
        - name: repo-init
          image: alpine/git
          args:
            - clone
            - -b "{{BRANCH}}"
            - --single-branch
            - --
            - git@bitbucket.org:{{MY_REPO}}
            - /data
          volumeMounts:
            - mountPath: /data
              name: repo-files
            - mountPath: /root/.ssh
              name: ssh-secret-files
              readOnly: true
```

And I'm getting this error:

```
Cloning into '/data'...
Host key verification failed.
fatal: Could not read from remote repository.
```

So, it seems we are missing to generate known_hosts file
Any example of how to accomplish it with this image?
