### ISSUE TITLE
Monthly builds are not running

### ISSUE THREAD

**Issue by gaby** [alpine-docker/git#58]
The latest tag for this image is from 4 months ago, the CI may need to be updated to use the new one from the `socat` repo.

**Comment by ozbillwang** [comment]
<img width="988" alt="image" src="https://user-images.githubusercontent.com/8954908/228092227-4dacd4b1-13c6-4dd0-9e00-5101c5cb23a7.png">

Need time to switch to other free pipeline

**Comment by gaby** [comment]
@ozbillwang Switch to github actions, its free for OSS projects

**Comment by gaby** [comment]
https://docs.docker.com/build/ci/github-actions/multi-platform/

**Comment by ozbillwang** [comment]
the GitHub action doesn't work well with multi-arch build. I did in Circle CI and will switch to it.

**Comment by gaby** [comment]
Multiarch builds are supported via buildx and qemu. The example from the link builds both linux/amd64 and linux/arm64

**Comment by ozbillwang** [comment]
ok, I run the test and the build is fine and put to hub.docker.com, 

https://github.com/alpinehub/git/blob/master/.github/workflows/main.yaml

But not to ghcr.io container registry. 

https://github.com/alpinehub/git/actions/runs/4519934168/jobs/7960767322

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/8954908/228121413-a878c090-2076-4e4f-8409-cfc1c085814f.png">

**Comment by gaby** [comment]
@ozbillwang Try this:

```yaml
name: Create and publish a Docker image

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:
  release:
    types: [published, edited]

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ozbillwang/git
            ghcr.io/ozbillwang/git
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: release
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/arm/v6,linux/ppc64le,linux/s390x
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
